# VERSION=v1.0.0 envsubst < deployment_gke.yaml | kubectl apply -f -

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dart-pubsub-gke-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dart-pubsub-gke-demo
  template:
    metadata:
      labels:
        app: dart-pubsub-gke-demo
    spec:
      containers:
        - name: capitalizer
          image: ${REGION}-docker.pkg.dev/${PROJECT}/${REPOSITORY}/capitalizer:${VERSION}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/keys/key.json
            - name: PROJECT
              value: ${PROJECT}
          volumeMounts:
            - name: keys
              mountPath: "/app/keys"
              readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: capitalizer
