# VERSION=v1.0.0 envsubst < deployment_gke.yaml | kubectl apply -f -

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitalizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitalizer
  template:
    metadata:
      labels:
        app: capitalizer
    spec:
      containers:
        - name: capitalizer
          image: ${REGION}-docker.pkg.dev/${PROJECT}/${REPOSITORY}/capitalizer:${VERSION}
          env:
            - name: PROJECT
              value: ${PROJECT}
          volumeMounts:
            - name: keys
              mountPath: "/app/keys"
              readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: capitalizer
