on:
  - workflow_dispatch

#environment: prod

jobs:
  get_environment_values:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      project: ${{ vars.PROJECT }}
      project_number: ${{ vars.PROJECT_NUMBER }}
    steps:
      #- run: echo ${{ vars.PROJECT }}
      - run: true

  generate_deployment_values:
    uses: ./.github/workflows/generate_deployment_values.yaml
    needs: env_test

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - get_environment_values
      - generate_deployment_values
    with:
      project: ${{ needs.get_environment_values.outputs.project }}
      project_number: ${{ needs.get_environment_values.output.project_number }}
      timestamp: ${{ needs.generate_deployment_values.outputs.timestamp }}
    secrets: inherit
    permissions:
      id-token: write

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - get_environment_values
      - deploy
    with:
      project: ${{ needs.get_environment_values.outputs.project }}
      project_number: ${{ needs.get_environment_values.output.project_number }}
    permissions:
      id-token: write
