on:
  - workflow_dispatch

jobs:
  get_environment_values:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      project: ${{ vars.PROJECT }}
    steps:
      - run: true

  generate_deployment_values:
    uses: ./.github/workflows/generate_deployment_values.yaml

  maybe_create_project:
    uses: ./.github/workflows/maybe_create_project.yaml
    needs:
      - get_environment_values
    with:
      project: ${{ needs.get_environment_values.outputs.project }}
    secrets: inherit
    permissions:
      id-token: write

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - generate_deployment_values
      - get_environment_values
      - maybe_create_project
    with:
      project: ${{ needs.get_environment_values.outputs.project }}
      project_number: ${{ needs.maybe_create_project.outputs.project_number }}
      timestamp: ${{ needs.generate_deployment_values.outputs.timestamp }}
    secrets: inherit
    permissions:
      id-token: write

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - deploy
      - get_environment_values
      - maybe_create_project
    with:
      project: ${{ needs.get_environment_values.outputs.project }}
      project_number: ${{ needs.maybe_create_project.outputs.project_number }}
    permissions:
      id-token: write
