on:
  - workflow_dispatch

#environment: prod

jobs:
  env_test:
    environment: prod
    steps:
      - run: echo ${{ vars.PROJECT }}
      - run: false

  generate_deployment_values:
    uses: ./.github/workflows/generate_deployment_values.yaml
    needs: env_test

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - generate_deployment_values
    with:
      project: ${{ vars.PROJECT }}
      project_number: ${{ vars.PROJECT_NUMBER }}
      timestamp: ${{ needs.generate_deployment_values.outputs.timestamp }}
    secrets: inherit
    permissions:
      id-token: write

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - deploy
    with:
      project: ${{ vars.PROJECT }}
      project_number: ${{ vars.PROJECT_NUMBER }}
    permissions:
      id-token: write
