on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      project_number:
        required: false
        type: string
      timestamp:
        required: true
        type: string
    secrets:
      BILLING_ACCOUNT:
        required: true
      MASTER_PROJECT_NAME:
        required: true
      MASTER_PROJECT_NUMBER:
        required: true

jobs:
  _:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: 'Export the environment variables'
        run: |
          echo "DART_VERSION=${{ vars.DART_VERSION }}" >> $GITHUB_ENV
          echo "PROJECT=${{ inputs.project }}" >> $GITHUB_ENV
          echo "PROJECT_NUMBER=${{ inputs.project_number }}" >> $GITHUB_ENV
          echo "REGION=${{ vars.REGION }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "TIMESTAMP=${{ inputs.timestamp }}" >> $GITHUB_ENV
          echo "ZONE=${{ vars.ZONE }}" >> $GITHUB_ENV

      - uses: 'google-github-actions/auth@v2'
        with:
#          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
#          service_account: 'deploy@${{ env.PROJECT }}.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/${{ secrets.MASTER_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'project-creator@${{ secrets.MASTER_PROJECT_NAME }}.iam.gserviceaccount.com'

      - name: 'Create the Google Cloud Project if it does not exist'
        id: create_project
        run: |
          # gcloud projects list # TODO: Delete
          set +e
          gcloud projects \
            create $PROJECT \
            --name=$PROJECT \
            --organization=${{ secrets.ORGANIZATION }}
          export EXIT_CODE=$?
          set -e
          echo "Exit code: $EXIT_CODE"
          if [ $EXIT_CODE -eq 0 ]; then
            echo "created=true" >> $GITHUB_OUTPUT
          else
            echo "created=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Get the project number'
        if: env.PROJECT_NUMBER == ''
        run: |
          export PROJECT_NUMBER=$(gcloud projects describe $PROJECT --format='value(projectNumber)')
          echo "Project Number: $PROJECT_NUMBER"
          echo "PROJECT_NUMBER=$PROJECT_NUMBER" >> $GITHUB_ENV

      - name: 'Enable the services'
        #if: steps.create_project.created == 'true'
        run: |
          gcloud services enable cloudbilling.googleapis.com --project=$PROJECT
          gcloud services enable artifactregistry.googleapis.com --project=$PROJECT
          gcloud services enable cloudbuild.googleapis.com --project=$PROJECT
          gcloud services enable cloudresourcemanager.googleapis.com --project=$PROJECT
          gcloud services enable container.googleapis.com --project=$PROJECT
          gcloud services enable iam.googleapis.com --project=$PROJECT
          gcloud services enable pubsub.googleapis.com --project=$PROJECT

      - name: 'Set the billing account'
        if: steps.create_project.created == 'true'
        run: |          
          gcloud billing \
            projects link $PROJECT \
            --billing-account=${{ secrets.BILLING_ACCOUNT }}

      - name: 'Create the state bucket for Terraform if it does not exist'
        #if: steps.create_project.created == 'true'
        run: |
          BUCKET="gs://$PROJECT-tf-state"
          if gsutil ls $BUCKET > /dev/null; then
            echo "Exists."
          else
            echo "Creating."
            gcloud storage \
              buckets create $BUCKET \
              --location=$REGION \
              --uniform-bucket-level-access \
              --project=$PROJECT
          fi

      - name: 'Create the service account for Terraform if it does not exist'
        run: |
          EMAIL=deploy@$PROJECT.iam.gserviceaccount.com
          if gcloud iam service-accounts list --project=$PROJECT | grep "$EMAIL"; then
            echo "Exists."
          else
            echo "Creating."
            gcloud iam \
              service-accounts create "deploy" \
              --project=$PROJECT
            gcloud projects \
              add-iam-policy-binding $PROJECT \
              --member="serviceAccount:$EMAIL" \
              --role="roles/owner" \
              --project=$PROJECT
          fi

      - name: 'Reading the deployers list'
        run: |
          input_file="infrastructure/deployers.txt"
          output=""
          while IFS= read -r line; do
            trimmed=$(echo "$line" | xargs)
            if [ -z "$output" ]; then
              output="'$trimmed'"
            else
              output="$output,'$trimmed'"
            fi
          done < "$input_file"
          echo "$output"
          echo "GITHUB_USERS_STR=$output" >> $GITHUB_ENV

      - name: 'Configure Workload Identity Federation for deployment'
        run: |
          gcloud iam \
            workload-identity-pools create "github" \
            --location="global" \
            --project=$PROJECT || true
          MAPPING=(
            'google.subject=assertion.sub'
            'attribute.actor=assertion.actor'
            'attribute.repository=assertion.repository'
          );gcloud iam \
            workload-identity-pools providers create-oidc "github" \
            --attribute-mapping="$(echo $(IFS=,; echo "${MAPPING[*]}"))" \
            --issuer-uri="https://token.actions.githubusercontent.com" \
            --location="global" \
            --workload-identity-pool="github" \
            --project=$PROJECT || true
          envsubst < infrastructure/deploy-policy.json | \
            gcloud iam \
              service-accounts set-iam-policy \
              deploy@$PROJECT.iam.gserviceaccount.com \
              /dev/stdin

#      - name: 'Sign out of Google Cloud'
#        run: |
#          gcloud auth revoke --all

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'deploy@${{ env.PROJECT }}.iam.gserviceaccount.com'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - run: terraform fmt -check -recursive
        continue-on-error: true

      - name: 'Allocate a version'
        run: |
          export APP_VERSION=$(grep '^version:' capitalizer/pubspec.yaml | awk '{print $2}');
          export COMMIT_HASH=$(git rev-parse HEAD)
          export VERSION="v$APP_VERSION-$TIMESTAMP-$COMMIT_HASH"
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 'Wait until IAM policy takes effect'
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e
        with:
          timeout_minutes: 1
          max_attempts: 5
          retry_wait_seconds: 60
          command: |
            gcloud projects list
            #gcloud artifacts repositories list

      - name: 'Create the Artifact Registry repository if it does not exist'
        run: |
          if gcloud artifacts repositories list --location=$REGION --filter="name:my-repository"; then
            echo "Exists."
          else
            echo "Creating."
            gcloud artifacts \
              repositories create my-repository \
              --repository-format=DOCKER \
              --location=$REGION \
              --project=$PROJECT
          fi

      - name: 'Submit a build'
        run: |
          SUBSTITUTIONS=(
            "_VERSION=$VERSION"
            "_DART_VERSION=$DART_VERSION"
            "_REGION=$REGION"
            "_REPOSITORY=my-repository"
          ); gcloud builds \
            submit \
            --project=$PROJECT \
            --substitutions="$(echo $(IFS=,; echo "${SUBSTITUTIONS[*]}"))" \
            --config=capitalizer/cloudbuild.yaml \
            capitalizer

      - name: 'Terraform'
        run: |
          cd infrastructure/terraform
          envsubst < backend.tf.template > backend.tf
          terraform init
          terraform apply \
            -auto-approve \
            -var="PROJECT=$PROJECT" \
            -var="REGION=$REGION" \
            -var="ZONE=$ZONE" \
            -var="VERSION=$VERSION"
