on:
  - workflow_dispatch

jobs:
  generate_deployment_values:
    uses: ./.github/workflows/generate_deployment_values.yaml

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - generate_deployment_values
    with:
      project: ${{ secrets.PROD_PROJECT }}
      project_number: ${{ secrets.PROD_PROJECT_NUMBER }}
      timestamp: ${{ needs.generate_deployment_values.outputs.timestamp }}
    secrets: inherit
    permissions:
      id-token: write

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - deploy
    with:
      project: ${{ secrets.PROD_PROJECT }}
      project_number: ${{ secrets.PROD_PROJECT_NUMBER }}
    permissions:
      id-token: write
