on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

    outputs:
      project_number:
        value: ${{ jobs._.outputs.project_number }}

    secrets:
      MASTER_PROJECT:
        required: true
      MASTER_PROJECT_NUMBER:
        required: true

jobs:
  _:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    outputs:
      project_number: ${{ steps.get.outputs.value }}

    steps:
      - name: 'Export the environment variables'
        run: |
          echo "PROJECT=${{ inputs.project }}" >> $GITHUB_ENV

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.MASTER_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'project-creator@${{ secrets.MASTER_PROJECT }}.iam.gserviceaccount.com'

      - name: 'Create the Google Cloud Project if it does not exist'
        run: |
          set +e # Continue on error.
          gcloud projects \
            create $PROJECT \
            --name=$PROJECT \
            --organization=${{ secrets.ORGANIZATION }}
          true # Exits with zero code so that the step is considered successful.

      - name: 'Get the project number'
        id: get
        run: |
          export PROJECT_NUMBER=$(gcloud projects describe $PROJECT --format='value(projectNumber)')
          echo "Project Number: $PROJECT_NUMBER"
          echo "value=$PROJECT_NUMBER" >> $GITHUB_OUTPUT
