on:
#  - workflow_call:
#      outputs:
#        output_param:
#          description: "Project ID"
#          value: ${{ steps.step1.outputs.output_value }}
  - workflow_dispatch

env:
  TF_LOG: DEBUG

jobs:
  generate_project_id:
    uses: ./.github/workflows/generate_project_id.yaml

  default:
    runs-on: ubuntu-latest
    needs: generate_project_id
    steps:
      - run: echo ${{ needs.generate_project_id.outputs.project }}
      - run: echo ${{ needs.generate_project_id.outputs.timestamp }}
