on:
  - workflow_dispatch

jobs:
  generate_deployment_values:
    uses: ./.github/workflows/generate_deployment_values.yaml

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - generate_deployment_values
    with:
      project: ${{ needs.generate_deployment_values.output.project }}
      timestamp: ${{ needs.generate_deployment_values.outputs.timestamp }}
    secrets: inherit
    permissions:
      id-token: write

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - deploy
    with:
      project: ${{ needs.generate_deployment_values.outputs.project }}
      project_number: ${{ needs.deploy.outputs.project_number }}
    permissions:
      id-token: write

  delete:
    uses: ./.github/workflows/delete.yaml
    needs:
      - test
    if: always()
    with:
      project: ${{ needs.generate_deployment_values.outputs.project }}
      project_number: ${{ needs.deploy.outputs.project_number }}
    permissions:
      id-token: write
