on:
  - workflow_dispatch

#env:
#  project: 'projects/${{ secrets.MASTER_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
#  project_number: 'project-creator@${{ secrets.MASTER_PROJECT_NAME }}.iam.gserviceaccount.com'

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      project: ${{ vars.DART_VERSION }}
      project_number: ${{ vars.ZONE }}

  _:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.MASTER_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'project-creator@${{ secrets.MASTER_PROJECT_NAME }}.iam.gserviceaccount.com'

      - uses: 'google-github-actions/setup-gcloud@v2'
      - run: gcloud info
      - run: gcloud projects list > /dev/null
